### ISSUE TITLE
В сравнении используется неоптимальный однострочник

### ISSUE THREAD

**Issue by sirikid** [yarkovaleksei/passgen#4]
Предлагаю такой вариант:

    cat /dev/urandom | tr -c -d [:alnum:] | head -c 30; echo

Так же вызывает вопрос юзкейс, генерирование большого количества однотипных паролей, где это востребованно?

**Comment by yarkovaleksei** [comment]
Ваш вариант:
```bash
$ time cat /dev/urandom | tr -c -d [:alnum:] | head -c 30; echo
c3p3FLZdEW63uWVwv3PJXUoQfbb3mt
real	0m0.033s
user	0m0.000s
sys	0m0.036s
```
Мой вариант:
```bash
$ time strings /dev/urandom | grep -o '[[:alnum:]]' | head -n 30 | tr -d '\n'; echo
v8S5crfttUNl1zrKAoTSmrakKoDOyz
real	0m0.042s
user	0m0.024s
sys	0m0.032s
```

Вы правы, ваш немного оптимальнее. Но в скорости все равно не сравнить.

- - -
```bash
$ time for i in {1..100};do cat /dev/urandom | tr -c -d [:alnum:] | head -c 30 > /dev/null; done
real	0m2.490s
user	0m0.248s
sys	0m2.756s
```

```bash
$ time passgen -l30 -u -d -n -c100 > /dev/null
real	0m0.005s
user	0m0.000s
sys	0m0.000s
```
- - -
А юзкейс... Ну первое, что приходит в голову, это генерация каких-то фейковых данных в больших количествах. Например пар **логин:пароль** (у меня раньше был такой web сервис). А сейчас думаю использовать для десктопного клиента для моего web сервиса [data-keeper.ru](https://data-keeper.ru).

А вообще это была проба пера так сказать. Первый раз на C писал.

**Comment by sirikid** [comment]
Улучшенный вариант:

    $ # 100 паролей по 30 символов
    $ cat /dev/urandom | tr -c -d [:alnum:] | head -c 3000 | sed -E 's/(.{30})/\1\n/'

```sh
# Первый параметр длина пароля, по умолчанию 25
# Второй параметр количество паролей, по умолчанию 1
passgen () {
    cat /dev/urandom | tr -c -d [:alnum:] | head -c $((${1:-25} * ${2:-1})) | sed -E "s/(.{${1:-25}})/\1\n/"
}
```

**Comment by yarkovaleksei** [comment]
Вы оптимизатор от Бога :smile: 
Просто отличный пример. Обновлю README. 

Спасибо за науку.
